### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by qixiang**

### CODE REVIEW

**Comment by qixiang** [comment]
@gnaponie @staticf0x @FernandesMF with this CODEOWNERS file, you'll be requested for review (automatically) when a PR is opened in this repo, if you don't want to be listed, please let me know.

**Comment by staticf0x** [comment]
I don't mind this but since this repo contains the controller written in Go and I don't understand Go syntax, I probably won't be of much help during reviews.

**Comment by gnaponie** [comment]
@qixiang could you add @nvtnlucie too? 
@staticf0x Unfortunately I believe this is true for all (or almost) of us :(

**Comment by qixiang** [comment]
@gnaponie Done.

@staticf0x Thanks for letting me know, that's totally fine, I'll keep you on the list, you can ignore the review requests, or feel free to review any parts you're comfortable with.

**Pull request merged**
